//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('hackathons')
export class hackathonsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  sponsor: number;

  @Column('integer', { nullable: true })
  participantsOrTeams: number;

  @Column('integer', { nullable: true })
  maxAndMinParticipantsNumberForEachTeam: number;

  @Column('text', { nullable: true })
  awards: string;

  @Column('text', { nullable: true })
  bio: string;

  @Column('text', { nullable: true })
  specialties: string;

  @Column('date', { nullable: true })
  datesOfStages: Date;

  @Column('integer', { nullable: true })
  arbitrators: number;

  @Column('integer', { nullable: true })
  collaboratingSponsors: number;

  @Column('text', { nullable: true })
  status: string;

  @Column('integer', { nullable: true })
  rankingOfParticipants: number;

  @Column('integer', { nullable: true })
  followers: number;
}
