//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('sponsors')
export class sponsorsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  sponsorId: number;

  @Column('text', { nullable: true })
  sponsorName: string;

  @Column('text', { nullable: true })
  sponsorLogo: string;

  @Column('text', { nullable: true })
  specialties: string;

  @Column('text', { nullable: true })
  website: string;

  @Column('text', { nullable: true })
  email: string;

  @Column('text', { nullable: true })
  phoneNumber: string;

  @Column('text', { nullable: true })
  address: string;

  @Column('text', { nullable: true })
  posts: string;

  @Column('integer', { nullable: true })
  previousHackathons: number;

  @Column('integer', { nullable: true })
  followers: number;

  @Column('integer', { nullable: true })
  followings: number;

  @Column('integer', { nullable: true })
  newHackathon: number;
}
