//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('teams')
export class teamsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  leaderParticipant: number;

  @Column('integer', { nullable: true })
  participant: number;

  @Column('integer', { nullable: true })
  previousHackathons: number;

  @Column('text', { nullable: true })
  awards: string;

  @Column('date', { nullable: true })
  dateOfCreation: Date;
}
