//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const hackathonsTitle = () => {
  const record = useRecordContext();
  return <span>hackathons {record ? `"${record.sponsor}"` : ''}</span>;
};

export const hackathonsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="sponsor" reference="sponsors" />
      <ReferenceField source="participantsOrTeams" reference="participants" />
      <ReferenceField
        source="maxAndMinParticipantsNumberForEachTeam"
        reference="teams"
      />
      <TextField source="awards" />
      <TextField source="bio" />
      <TextField source="specialties" />
      <DateField source="datesOfStages" />
      <ReferenceField source="arbitrators" reference="participants" />
      <ReferenceField source="collaboratingSponsors" reference="sponsors" />
      <TextField source="status" />
      <ReferenceField source="rankingOfParticipants" reference="participants" />
      <ReferenceField source="followers" reference="participants" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const hackathonsEdit = () => (
  <Edit title={<hackathonsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="sponsor" reference="sponsors" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="participantsOrTeams"
            reference="participants"
          />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="maxAndMinParticipantsNumberForEachTeam"
            reference="teams"
          />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="awards" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="bio" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="specialties" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="datesOfStages" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="arbitrators" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="collaboratingSponsors" reference="sponsors" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="status" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="rankingOfParticipants"
            reference="participants"
          />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="followers" reference="participants" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const hackathonsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="sponsor" reference="sponsors" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="participantsOrTeams"
            reference="participants"
          />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="maxAndMinParticipantsNumberForEachTeam"
            reference="teams"
          />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="awards" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="bio" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="specialties" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="datesOfStages" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="arbitrators" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="collaboratingSponsors" reference="sponsors" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="status" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput
            source="rankingOfParticipants"
            reference="participants"
          />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="followers" reference="participants" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="sponsor"
    label="sponsor"
    reference="sponsors"
    alwaysOn
  />,
  <ReferenceInput
    source="participantsOrTeams"
    label="participantsOrTeams"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="maxAndMinParticipantsNumberForEachTeam"
    label="maxAndMinParticipantsNumberForEachTeam"
    reference="teams"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="arbitrators"
    label="arbitrators"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="collaboratingSponsors"
    label="collaboratingSponsors"
    reference="sponsors"
    alwaysOn
  />,
  ,
  <ReferenceInput
    source="rankingOfParticipants"
    label="rankingOfParticipants"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="followers"
    label="followers"
    reference="participants"
    alwaysOn
  />,
];
