//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const sponsorsTitle = () => {
  const record = useRecordContext();
  return <span>sponsors {record ? `"${record.sponsorName}"` : ''}</span>;
};

export const sponsorsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="sponsorId" />
      <TextField source="sponsorName" />
      <ImageField source="sponsorLogo" />
      <TextField source="specialties" />
      <UrlField source="website" />
      <EmailField source="email" />
      <TextField source="phoneNumber" />
      <TextField source="address" />
      <TextField source="posts" />
      <ReferenceField source="previousHackathons" reference="hackathons" />
      <ReferenceField source="followers" reference="participants" />
      <ReferenceField source="followings" reference="participants" />
      <ReferenceField source="newHackathon" reference="hackathons" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const sponsorsEdit = () => (
  <Edit title={<sponsorsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="sponsorId" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="sponsorName" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="sponsorLogo" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="specialties" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="website" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="email" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="phoneNumber" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="address" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="posts" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="previousHackathons" reference="hackathons" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="followers" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="followings" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="newHackathon" reference="hackathons" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const sponsorsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="sponsorId" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="sponsorName" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="sponsorLogo" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="specialties" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="website" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="email" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="phoneNumber" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="address" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="posts" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="previousHackathons" reference="hackathons" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="followers" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="followings" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="newHackathon" reference="hackathons" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="previousHackathons"
    label="previousHackathons"
    reference="hackathons"
    alwaysOn
  />,
  <ReferenceInput
    source="followers"
    label="followers"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="followings"
    label="followings"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="newHackathon"
    label="newHackathon"
    reference="hackathons"
    alwaysOn
  />,
];
