//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const teamsTitle = () => {
  const record = useRecordContext();
  return <span>teams {record ? `"${record.leaderParticipant}"` : ''}</span>;
};

export const teamsList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="leaderParticipant" reference="participants" />
      <ReferenceField source="participant" reference="participants" />
      <ReferenceField source="previousHackathons" reference="hackathons" />
      <TextField source="awards" />
      <DateField source="dateOfCreation" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const teamsEdit = () => (
  <Edit title={<teamsTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="leaderParticipant" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="participant" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="previousHackathons" reference="hackathons" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="awards" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfCreation" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const teamsCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="leaderParticipant" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="participant" reference="participants" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="previousHackathons" reference="hackathons" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="awards" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfCreation" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="leaderParticipant"
    label="leaderParticipant"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="participant"
    label="participant"
    reference="participants"
    alwaysOn
  />,
  <ReferenceInput
    source="previousHackathons"
    label="previousHackathons"
    reference="hackathons"
    alwaysOn
  />,
  ,
  ,
];
