//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  participantsList,
  participantsCreate,
  participantsEdit,
} from './resources/participants';
import {
  sponsorsList,
  sponsorsCreate,
  sponsorsEdit,
} from './resources/sponsors';
import { teamsList, teamsCreate, teamsEdit } from './resources/teams';
import {
  hackathonsList,
  hackathonsCreate,
  hackathonsEdit,
} from './resources/hackathons';
import participantsIcon from '@mui/icons-material/People';
import sponsorsIcon from '@mui/icons-material/Business';
import teamsIcon from '@mui/icons-material/Group';
import hackathonsIcon from '@mui/icons-material/Event';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/adbd1cb27">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="participants"
          options={{ label: 'Participants' }}
          list={participantsList}
          create={participantsCreate}
          edit={participantsEdit}
          recordRepresentation="fullName"
          icon={participantsIcon}
        />
        <Resource
          name="sponsors"
          options={{ label: 'Sponsors' }}
          list={sponsorsList}
          create={sponsorsCreate}
          edit={sponsorsEdit}
          recordRepresentation="sponsorName"
          icon={sponsorsIcon}
        />
        <Resource
          name="teams"
          options={{ label: 'Teams' }}
          list={teamsList}
          create={teamsCreate}
          edit={teamsEdit}
          recordRepresentation="leaderParticipant"
          icon={teamsIcon}
        />
        <Resource
          name="hackathons"
          options={{ label: 'Hackathons' }}
          list={hackathonsList}
          create={hackathonsCreate}
          edit={hackathonsEdit}
          recordRepresentation="sponsor"
          icon={hackathonsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
