//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Hackathonz" />
    <CardContent>
      Application that similar to LinkedIn, it is directed to students or any
      people who wants to be a participant in the hackathons, so they go to the
      application and it shows who could be interested in, or participant who
      have an idea and need a team, or the sponsors who wants to announcing the
      hackathon
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
