//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    participants: {
      name: 'Participants',
      fields: {
        participantId: 'Participant Id',
        fullName: 'Full Name',
        email: 'Email',
        phone: 'Phone',
        city: 'City',
        profilePicture: 'Profile Picture',
        dateOfBirth: 'Date Of Birth',
        gender: 'Gender',
        bio: 'Bio',
        skills: 'Skills',
        previousHackathons: 'Previous Hackathons',
        schoolOrParty: 'School Or Party',
        awards: 'Awards',
        languages: 'Languages',
        interests: 'Interests',
        teamsSignedUpFor: 'Teams Signed Up For',
        posts: 'Posts',
        following: 'Following',
        followers: 'Followers',
        directMessages: 'Direct Messages',
        settings: 'Settings',
        specialties: 'Specialties',
        socialMediaAccounts: 'Social Media Accounts',
        createTeam: 'Create Team',
        id: 'id',
      },
    },
    sponsors: {
      name: 'Sponsors',
      fields: {
        sponsorId: 'Sponsor Id',
        sponsorName: 'Sponsor Name',
        sponsorLogo: 'Sponsor Logo',
        specialties: 'Specialties',
        website: 'Website',
        email: 'Email',
        phoneNumber: 'Phone Number',
        address: 'Address',
        posts: 'Posts',
        previousHackathons: 'Previous Hackathons',
        followers: 'Followers',
        followings: 'Followings',
        newHackathon: 'New Hackathon',
        id: 'id',
      },
    },
    teams: {
      name: 'Teams',
      fields: {
        leaderParticipant: 'Leader Participant',
        participant: 'Participant',
        previousHackathons: 'Previous Hackathons',
        awards: 'Awards',
        dateOfCreation: 'Date Of Creation',
        id: 'id',
      },
    },
    hackathons: {
      name: 'Hackathons',
      fields: {
        sponsor: 'Sponsor',
        participantsOrTeams: 'Participants Or Teams',
        maxAndMinParticipantsNumberForEachTeam:
          'Max And Min Participants Number For Each Team',
        awards: 'Awards',
        bio: 'Bio',
        specialties: 'Specialties',
        datesOfStages: 'Dates Of Stages',
        arbitrators: 'Arbitrators',
        collaboratingSponsors: 'Collaborating Sponsors',
        status: 'Status',
        rankingOfParticipants: 'Ranking Of Participants',
        followers: 'Followers',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    participants: {
      name: 'Participants (fr)',
      fields: {
        participantId: 'Participant Id (fr)',
        fullName: 'Full Name (fr)',
        email: 'Email (fr)',
        phone: 'Phone (fr)',
        city: 'City (fr)',
        profilePicture: 'Profile Picture (fr)',
        dateOfBirth: 'Date Of Birth (fr)',
        gender: 'Gender (fr)',
        bio: 'Bio (fr)',
        skills: 'Skills (fr)',
        previousHackathons: 'Previous Hackathons (fr)',
        schoolOrParty: 'School Or Party (fr)',
        awards: 'Awards (fr)',
        languages: 'Languages (fr)',
        interests: 'Interests (fr)',
        teamsSignedUpFor: 'Teams Signed Up For (fr)',
        posts: 'Posts (fr)',
        following: 'Following (fr)',
        followers: 'Followers (fr)',
        directMessages: 'Direct Messages (fr)',
        settings: 'Settings (fr)',
        specialties: 'Specialties (fr)',
        socialMediaAccounts: 'Social Media Accounts (fr)',
        createTeam: 'Create Team (fr)',
        id: 'id',
      },
    },
    sponsors: {
      name: 'Sponsors (fr)',
      fields: {
        sponsorId: 'Sponsor Id (fr)',
        sponsorName: 'Sponsor Name (fr)',
        sponsorLogo: 'Sponsor Logo (fr)',
        specialties: 'Specialties (fr)',
        website: 'Website (fr)',
        email: 'Email (fr)',
        phoneNumber: 'Phone Number (fr)',
        address: 'Address (fr)',
        posts: 'Posts (fr)',
        previousHackathons: 'Previous Hackathons (fr)',
        followers: 'Followers (fr)',
        followings: 'Followings (fr)',
        newHackathon: 'New Hackathon (fr)',
        id: 'id',
      },
    },
    teams: {
      name: 'Teams (fr)',
      fields: {
        leaderParticipant: 'Leader Participant (fr)',
        participant: 'Participant (fr)',
        previousHackathons: 'Previous Hackathons (fr)',
        awards: 'Awards (fr)',
        dateOfCreation: 'Date Of Creation (fr)',
        id: 'id',
      },
    },
    hackathons: {
      name: 'Hackathons (fr)',
      fields: {
        sponsor: 'Sponsor (fr)',
        participantsOrTeams: 'Participants Or Teams (fr)',
        maxAndMinParticipantsNumberForEachTeam:
          'Max And Min Participants Number For Each Team (fr)',
        awards: 'Awards (fr)',
        bio: 'Bio (fr)',
        specialties: 'Specialties (fr)',
        datesOfStages: 'Dates Of Stages (fr)',
        arbitrators: 'Arbitrators (fr)',
        collaboratingSponsors: 'Collaborating Sponsors (fr)',
        status: 'Status (fr)',
        rankingOfParticipants: 'Ranking Of Participants (fr)',
        followers: 'Followers (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
